logging:
  file:
    path: /var/log/
    name: webdav.log
#    max-size: 200MB
#  level:
#    root: trace
#  level:
#    net:
#      sf:
#        webdav: trace

aliyundrive:
  auth:
    enable: true
    username: admin
    password: admin

server:
  tomcat:
    connection-timeout: 1d
  port: 8080
